### ISSUE TITLE
v2 fails on npm install

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#10]
### terminal output

```
» npm install    
npm WARN package.json disaster-asset-manager@0.2.0 license should be a valid SPDX license expression
\
> sharp@0.10.1 install /Users/danbjoseph/Documents/Github/AmericanRedCross/disaster-asset-manager/node_modules/sharp
> node-gyp rebuild

Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
gyp: Call to 'PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10:$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/danbjoseph/Documents/Github/AmericanRedCross/disaster-asset-manager/node_modules/sharp
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danbjoseph/Documents/Github/AmericanRedCross/disaster-asset-manager/npm-debug.log
```
### npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'vips' ]
2 info using npm@2.12.1
3 info using node@v0.12.6
4 verbose node symlink /usr/local/bin/node
5 verbose install initial load of /usr/local/lib/package.json
6 verbose readDependencies loading dependencies from /usr/local/lib/package.json
7 silly cache add args [ 'vips', null ]
8 verbose cache add spec vips
9 silly cache add parsed spec { raw: 'vips',
9 silly cache add   scope: null,
9 silly cache add   name: 'vips',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed vips@*
11 verbose addNamed "*" is a valid semver range for vips
12 silly addNameRange { name: 'vips', range: '*', hasData: false }
13 silly mapToRegistry name vips
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/vips
17 verbose addNameRange registry:https://registry.npmjs.org/vips not in flight; fetching
18 verbose request uri https://registry.npmjs.org/vips
19 verbose request no auth needed
20 info attempt registry request try #1 at 13:38:27
21 verbose request id 082a05f1b191e4f3
22 http request GET https://registry.npmjs.org/vips
23 http 404 https://registry.npmjs.org/vips
24 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   'cache-control': 'max-age=0',
24 verbose headers   'content-length': '51',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Sun, 05 Jul 2015 17:38:27 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   age: '0',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-atl6232-ATL',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1436117907.653515,VS0,VE93' }
25 silly get cb [ 404,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     'content-type': 'application/json',
25 silly get     'cache-control': 'max-age=0',
25 silly get     'content-length': '51',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Sun, 05 Jul 2015 17:38:27 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-atl6232-ATL',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1436117907.653515,VS0,VE93' } ]
26 verbose stack Error: 404 Not Found: vips
26 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:245:14)
26 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
26 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:197:22)
26 verbose stack     at Request.emit (events.js:110:17)
26 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1050:14)
26 verbose stack     at Request.emit (events.js:129:20)
26 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:996:12)
26 verbose stack     at IncomingMessage.emit (events.js:129:20)
26 verbose stack     at _stream_readable.js:908:16
26 verbose stack     at process._tickCallback (node.js:355:11)
27 verbose statusCode 404
28 verbose pkgid vips
29 verbose cwd /Users/danbjoseph/Documents/Github/AmericanRedCross/disaster-asset-manager
30 error Darwin 14.4.0
31 error argv "node" "/usr/local/bin/npm" "install" "-g" "vips"
32 error node v0.12.6
33 error npm  v2.12.1
34 error code E404
35 error 404 Not Found: vips
35 error 404
35 error 404 'vips' is not in the npm registry.
35 error 404 You should bug the author to publish it (or use the name yourself!)
35 error 404
35 error 404 Note that you can also install from a
35 error 404 tarball, folder, http url, or git url.
36 verbose exit [ 1, true ]
```

**Comment by kevinlustig** [comment]
Yes, apologies - libvips is a dependency of one of the modules. I need to
add that to the documentation. For the moment, take a look at the
documentation for the Sharp module. It has a libvips install script that I
found handy, and which we might want to co-opt.

**Comment by danbjoseph** [comment]
https://www.npmjs.com/package/sharp#mac-os-tips
